# Configuration de la base de données MariaDB
# Modifier ces valeurs selon votre environnement


# Adresse du serveur MariaDB
DB_HOST=""


# Port du serveur (par défaut: 3306)
DB_PORT=3306


# Nom d'utilisateur
DB_USER="desgranges"


# Mot de passe
DB_PASSWORD="desgranges"


# Nom de la base de données
DB_NAME=""
